config/routes.rb
Rails.application.routes.draw do
    # This route sends requests to our naked url to the *cool* action in the *gif* controller.
    root 'restaurants#index'
    get '/login', to: 'sessions#new', as: :login
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'

    # These routes will be for signup. The first renders a form in the browse, the second will
    # receive the form and create a user in our database using the data given to us by the user.
    get '/signup' => 'users#new'
    post '/users' => 'users#create'

  resources :restaurants, only: [:index, :create, :new, :show] do
    resources :reviews, only: [:create, :new]
  end

  namespace :admin do
    resources :restaurants do
      resources :reviews, only: [:create, :new]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = %w(chinese italian japanese french belgian)
  has_many :reviews, dependent: :destroy
  validates :name, :address, :phone_number, :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, numericality: true
  validates :rating, inclusion: { in: (0..5).to_a, allow_nil: false}
  validates :content, :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_action :check_admin
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    if @restaurant.save
      redirect_to admin_restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def show
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to admin_restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def check_admin
    redirect_to root_path unless current_user.admin
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController

  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    if @review.save
      redirect_to admin_restaurant(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path if current_user
  end

  def create
    user = User.find_by(email: params[:email])
    # If pthe user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to root_path
    else
      # If user's login doesn't work, send them back to the login form.
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
    end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/restaurants/_form.html.erb
<%= simple_form_for @restaurant, url: admin_restaurant_path, method: :patch do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, as: :select, collection: Restaurant::CATEGORIES, include_blank:  "Select a category" %>
  <%= f.submit %>
<% end %>

app/views/admin/restaurants/edit.html.erb
<%= render 'form' %>

app/views/admin/restaurants/index.html.erb
<h1>All restaurants</h1>

<% @restaurants.each do |restaurant| %>
  <%= link_to restaurant.name, admin_restaurant_path(restaurant)  %>
<% end %>


<%= link_to "New restaurant", new_admin_restaurant_path  %>

app/views/admin/restaurants/new.html.erb
<%= render 'form' %>

app/views/admin/restaurants/show.html.erb
<h2> <%= @restaurant.name %></h2>


<%= link_to "Edit", edit_admin_restaurant_path(@restaurant)  %>

<%= link_to "Delete", admin_restaurant_path(@restaurant), method: :delete  %>

<% if @restaurant.reviews %>
  <% @restaurant.reviews.each do |review| %>
    <p> <%= review.content %> </p>
    <p> <%= review.rating %></p>
  <% end %>
<% end %>

<%= link_to "Create a review", new_admin_restaurant_review_path(@restaurant)  %>

app/views/admin/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, as: :select, collection: (0..5).to_a, include_blank:  "Select a rating" %>
  <%= f.submit %>
<% end %>

app/views/extra/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src="https://avatars0.githubusercontent.com/u/16181471?v=4&s=460" class="avatar">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="" class="navbar-wagon-item navbar-wagon-link">Host</a>

    <!-- Profile picture with dropdown list -->
    <% if current_user %>
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" aria-hidden="true" data-toggle="dropdown" id="navbar-wagon-menu"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
         <li><a href="#">Signed in as <%= current_user.name.capitalize %> </a> </li>
         <li> <%= link_to "Logout", '/logout' %> </li>
        </ul>
      </div>
    </div>
    <% else %>
      <%= link_to 'Login', '/login', class: "btn btn-default btn-mine " %>  <%= link_to 'Signup', '/signup', class: "btn btn-success btn-mine" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'extra/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, as: :select, collection: Restaurant::CATEGORIES, include_blank:  "Select a category" %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://kitt.lewagon.com/placeholder/cities/berlin');">
  <div class="banner-content">
    <h1>Yelp</h1>
    <a class="btn btn-primary btn-lg">Find best restaurant</a>
  </div>
</div>


<div class="container">
  <div class="content">
    <h1 class="text-center">All restaurant</h1>
    <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-4">
        <!-- insert <div class="card"> -->
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://lorempixel.com/400/200/city/');">
          <div class="card-category">Popular</div>
            <div class="card-description">
             <h1><%=  restaurant.name.capitalize %></h1>
            </div>
          <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
          <a class="card-link" href="#" ></a>
          <%= link_to "", restaurant_path(restaurant), class: "card-link"  %>
        </div>
      </div>
        <% end %>
    </div>
  </div>
  <div class="content text-center">
  <%= link_to "New restaurant", new_restaurant_path, class: "btn btn-primary btn-lg"  %>
  </div>
</div>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<h2> <%= @restaurant.name %></h2>


<% if @restaurant.reviews %>
  <% @restaurant.reviews.each do |review| %>
    <p> <%= review.content %> </p>
    <p> <%= review.rating %></p>
  <% end %>
<% end %>

<%= link_to "Create a review", new_restaurant_review_path(@restaurant)  %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, as: :select, collection: (0..5).to_a, include_blank:  "Select a rating" %>
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= simple_form_for :user, url: '/users' do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>